### ISSUE TITLE
Icon bug

### ISSUE THREAD

**Issue by Kekk0x** [overextended/fivem-appearance#13]
This icon it's too bugged:
![Desktop Screenshot 2022 02 25 - 12 30 29 59](https://user-images.githubusercontent.com/100416558/155708878-8154bae2-57d6-44d6-9b90-f5fe75700e6d.png)

**Comment by LukeWasTakenn** [comment]
What?

**Comment by Kekk0x** [comment]
This icon doesn't work as it should. To turn the character you have to click this and then one of the three icons: head, half body or feet. when in reality why not an icon that makes the character turn in half without having to click anything other than this icon?

**Comment by Kekk0x** [comment]
this icon should do exactly that but unfortunately it does not work as it should 
https://www.youtube.com/watch?v=oaRJHevuYxs

**Comment by Kekk0x** [comment]
I hope I explained myself ... I'm Italian and I don't know English well, I ask forgiveness

**Comment by Kekk0x** [comment]
@LukeWasTakenn @0xDEMXN

**Comment by thelindat** [comment]
The button works exactly as designed, you rotate 180 degrees.
