### ISSUE TITLE
[BUG] TattoShop UI

### ISSUE THREAD

**Issue by CatalystDevs** [overextended/fivem-appearance#22]
![image](https://user-images.githubusercontent.com/100300495/158028122-068f0509-6135-419a-b39e-0f389edf0eae.png)

**Comment by N-fire** [comment]
![image](https://user-images.githubusercontent.com/55892717/158028159-b560df73-7f6c-4312-8a4a-e0858fb6caef.png)

**Comment by CatalystDevs** [comment]
Oh okey

**Comment by duckysuck** [comment]
I've got a simple tattoo script to now test this with. Going to jump on it tonight.
